swagger: '2.0'
host: 'localhost:6000'
basePath: /
schemes:
  - http
info:
  version: 1.0.0
  title: Ladjs
  description: API for Ladjs project
paths:
  /v1/account:
    get:
      description: Returns account details for current user
      responses:
        '200':
          description: A user object.
          schema:
            type: String
    put:
      description: Replaces account details for current user
      responses:
        '200':
          description: A user object.
          schema:
            type: String
